project:
  type: website
  output-dir: docs

website:
  title: "Applied Regression in R"
  navbar:
    left:
      - href: index.qmd
        text: Syllabus
      - href: completion-requirements.qmd
        text: Completion Requirements
      - text: Slides
        menu:
          - href: media/00-intro.pdf
            text: Introduction
          - href: media/01-simple-regression.pdf
            text: Simple Regression
          - href: media/02-multiple-regression.pdf
            text: Multiple Regression
          - href: media/03-interpretation.pdf
            text: Interpretation
          - href: media/04-uncertainty.pdf
            text: Uncertainty
          - href: media/05-hypothesis-testing.pdf
            text: Hypothesis Testing
          - href: media/06-model-fit.pdf
            text: Model Fit
          - href: media/07-modeling-goals.pdf
            text: DAGs
          - href: media/08-assumptions.pdf
            text: Model Assumptions
          - href: media/09-linearity.pdf
            text:  (Non)linearity
          - href: media/10-homoskedasticity-independence.pdf
            text: Homoskedasticity, Independence, Normality
      - text: Materials
        menu:
          - href: final-homework.qmd
            text: Final Homework
          - href: literature.qmd
            text: Literature
          - href: data.qmd
            text: Data
      - href: cheatsheets.qmd
        text: Cheatsheets
  page-footer:
    left: '<a href= "https://ksoc.ff.cuni.cz/"><img src="/media/ksoc-logo.svg" width="224" height="80" /></a>'
    
format:
  html:
    theme: [cosmo, styles.scss]
    toc: false

editor: visual

